set shell := ["bash", "-cu"]

@default:
    echo "Available Commands:"
    echo ""
    echo "  tests *args"
    echo "    Runs the test suite using pytest with the specified parameters."
    echo "    Usage:"
    echo "      tests [pytest-params]"
    echo "    Example:"
    echo "      tests -v --maxfail=2"
    echo ""
    echo "  report *args"
    echo "    Generates reports using the run.sh script."
    echo "    Usage:"
    echo "      report <Test_Category>"
    echo "    Valid Test Categories:"
    echo "      full, versioning, basic, policy, cold, locking, big-objects"
    echo "    Example:"
    echo "      report full"
    echo ""

setup-profiles:
    uv run ./bin/configure_profiles.py ./params.example.yaml

tests *pytest_params:
    just setup-profiles
    uv run pytest ./docs/*_test.py --config ./params.example.yaml {{pytest_params}}

report category:
    just setup-profiles
    bash -c "cd reports && ./run.sh {{category}} ../params.example.yaml ../docs/ && mv report_*.pdf outputs/"
