name: Nightly and Latest Tools Daily Tests

on:
  push:
    branches:
      - feat-add-nightely-latest-old-cli

  schedule:
    - cron: "0 * * * *"        # Every hour at 00 min
    - cron: "*/10 * * * *"
jobs:
  latest_tools_tests:
    if: github.event.schedule == '0 * * * *'  
    strategy:
      fail-fast: false
      matrix:
        marker:
          - test: basic
            name: basic
          # - test: cold_storage
          #   name: cold_storage
          # - test: presign
          #   name: presign
          # - test: acl
          #   name: acl
          # - test: locking
          #   name: locking
          # - test: policy
          #   name: policy
          # - test: bucket_versioning
          #   name: bucket_versioning
          # - test: multiple_objects
          #   name: multiple_objects
          # - test: big_objects
          #   name: big_objects
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_1hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
      container: "ghcr.io/magalucloud/s3-specs:tools_latest"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  nightly_tools_tests:
    if: github.event.schedule == '*/10 * * * *'
    strategy:
      fail-fast: false
      matrix:
        marker:
          - test: basic
            name: basic
          # - test: cold_storage
          #   name: cold_storage
          # - test: presign
          #   name: presign
          # - test: acl
          #   name: acl
          # - test: locking
          #   name: locking
          # - test: policy
          #   name: policy
          # - test: bucket_versioning
          #   name: bucket_versioning
          # - test: multiple_objects
          #   name: multiple_objects
          # - test: big_objects
          #   name: big_objects
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_6hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
      container: "ghcr.io/magalucloud/s3-specs:tools_nightly"
      runner: "self-hosted"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  cleanup-tests:
    needs: [latest_tools_tests, nightly_tools_tests]
    if: always() 
    uses: ./.github/workflows/cleanup-tests.yml
    secrets:
      PROFILES: ${{ secrets.PROFILES }}