name: Deploy Reports

on:
  push:
    branches: [temp-action-test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        run: |
          mkdir -p ./public
          cp -r reports_html/* ./public/
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public