name: Deploy Reports

on:
  push:
    branches: [temp-action-test]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: temp-action-test
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Copy reports
        run: |
          mkdir -p ./public
          cp -r reports_html/* ./public/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      
      - name: Deploy
        uses: actions/deploy-pages@v1