name: Build test OCI Image

on:
  workflow_call:
  push:
    branches:
      - main
      - feat-add-nightely-latest-old-cli
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: magalucloud/s3-specs

jobs:
  build-oldest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and push OCI image, tag: full"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tools_oldest.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:full
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:full-${{github.sha}}
  
  build-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and push OCI image, tag: tools_latest"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tools_latest.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools_latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools_latest-${{github.sha}}
  
  build-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and push OCI image, tag: tools_nightly"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tools_nightly.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools_nightly
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools_nightly-${{github.sha}}
