name: Build test OCI Image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: magalucloud/s3-specs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OCI image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: oci/${{ inputs.name }}.Containerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.name }}-${{ github.sha }}
