name: Build test OCI Image On Push

on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      packages: write  
      contents: read 
    strategy:
      max-parallel: 1
      matrix:
        include:
          - image: tools_oldest
            name: tools_oldest
          - image: tools_latest
            name: tools_latest
          - image: tools_nightly
            name: tools_nightly
          - image: tests_oldest
            name: tests_oldest
          - image: tests_latest
            name: tests_latest
          - image: tests_nightly
            name: tests_nightly
    uses: ./.github/workflows/generate-docker-image.yml
    with:
      name: ${{ matrix.name }}  