name: Build test OCI Image Dev on dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      mgc_branch:
        description: 'Branch do MGC CLI'
        required: true
        type: string

  workflow_call:
    inputs:
      name:
        required: true
        type: string
      mgc_branch:
        required: true
        type: string

jobs:
  build:
    permissions:
      packages: write  
      contents: read 
    strategy:
      max-parallel: 1
      matrix:
        include:
          - image: tools_dev
            name: tools_dev
          - image: tests_dev
            name: tests_dev
    uses: ./.github/workflows/generate-docker-image.yml
    with:
      name: ${{ matrix.name }}  
      mgc_branch: ${{ inputs.mgc_branch }}
