name: Manual Test

on:
    workflow_dispatch:
      inputs:
        tests:
          description: 'Digite o nome do arquivo de teste a ser executado'
          required: true
        config:
          description: 'Digite o caminho da configuração a ser utilizado'
          required: true
          default: ../../../params.example.yaml
        flags:
          description: 'Flags Adicionais'
          required: false
          default: --tb=line
        runner:
          description: 'Machine to run the tests'
          default: 'ubuntu-24.04'
          required: false
        mgc_version:
          description: 'Version of the MGC CLI'
          default: '0.34.0'
          required: false
        profile:
          description: 'Region to use for the tests'
          default: 'br-se1'
          required: false
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "manual_test"
      tests: ${{ inputs.tests }}
      config: ${{ inputs.config }}
      flags: ${{ inputs.flags }}
      runner: ${{ inputs.runner }}
      mgc_version: ${{ inputs.mgc_version }}
      profile: ${{ inputs.profile }}
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
