name: Manual Test

on:
    workflow_dispatch:
      inputs:
        tests:
          description: 'Digite o nome do arquivo de teste a ser executado'
          required: true
        config:
          description: 'Digite o caminho da configuração a ser utilizado'
          required: true
          default: ../../../params.example.yaml
        flags:
          description: 'Flags Adicionais'
          required: false
          default: --tb=line
        runner:
          description: 'Machine to run the tests'
          default: 'ubuntu-24.04'
          required: false
        container:
          description: 'Container to run the tests'
          type: choice
          default: 'ghcr.io/magalucloud/s3-specs:tools_oldest'
          options:
            - 'ghcr.io/magalucloud/s3-specs:tests_latest'
            - 'ghcr.io/magalucloud/s3-specs:tests_nightly'
            - 'ghcr.io/magalucloud/s3-specs:tests_oldest'
            - 'ghcr.io/magalucloud/s3-specs:tests_dev'

        profile:
          description: 'Profile em que os testes serão executados'
          type: choice
          default: 'homologacao'
          options:
            - 'homologacao'
            - 'br-se1'
            - 'br-ne1'
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "manual_test"
      tests: ${{ inputs.tests }}
      config: ${{ inputs.config }}
      flags: ${{ inputs.flags }}
      runner: ${{ inputs.runner }}
      container: ${{ inputs.container }}
      profile: ${{ inputs.profile }}
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
