name: Manual Test

on:
    workflow_dispatch:
      inputs:
        tests:
          description: 'Digite o nome do arquivo de teste a ser executado'
          required: true
        config:
          description: 'Digite o caminho da configuração a ser utilizado'
          required: true
          default: ../params.example.yaml
        flags:
          description: 'Flags Adicionais'
          required: false
          default: --tb=line
        runner:
          description: 'Machine to run the tests'
          default: 'ubuntu-24.04'
          required: false

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      tests: ${{ inputs.tests }}
      config: ${{ inputs.config }}
      flags: ${{ inputs.flags }}
      runner: ${{ inputs.runner }}
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
