name: Tests de Homologação

on:
  workflow_dispatch:
      inputs:
        container:
          description: 'Container to run the tests'
          type: choice
          default: 'ghcr.io/magalucloud/s3-specs:tools_latest'
          options:
            - 'ghcr.io/magalucloud/s3-specs:tests_latest'
            - 'ghcr.io/magalucloud/s3-specs:tests_oldest'
        profile:
          description: 'Profile em que os testes serão executados'
          type: choice
          default: 'br-ne1-yel'
          options:
            - 'br-ne1-yel'
            - 'br-se1'
            - 'br-ne1'

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        tools:
          - name: latest
            value: latest

        marker:
          - test: basic
            name: basic
          - test: cold_storage
            name: cold_storage
          - test: presign
            name: presign
          - test: acl
            name: acl
          - test: locking
            name: locking
          - test: policy
            name: policy
          - test: bucket_versioning
            name: bucket_versioning
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests-with-report.yml
    with:
      name: "${{ matrix.marker.name }}_1hours.${{ matrix.config.name }}"
      prefix_object_key: "homologacao"
      mark: ${{matrix.marker.test}}
      container: ${{ inputs.container }}
      profile: ${{ inputs.profile }}
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
