name: Notify GChat when PR is ready

on:
  pull_request:
    types: [ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install requests

      - name: Notify Google Chat
        run: |
            python bin/webhook-pr.py \
            --webhook-url "${{ secrets.WEBHOOK_PR_URL }}" \
            --pr-number "${{ github.event.pull_request.number }}" \
            --pr-title "${{ github.event.pull_request.title }}" \
            --pr-url "${{ github.event.pull_request.html_url }}" \
            --repo-name "${{ github.repository }}" \
            --pr-body '${{ toJson(github.event.pull_request.body) }}' \
            --pr-user "${{ github.event.pull_request.user.login }}"

