name: Optional Run Test - Pull Request

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # since locking is a feature currently under preview, we run it separatedely
  # and dont block merges if they fail
  run-locking-tests:
    strategy:
      fail-fast: false
      matrix:
        marker:
          - flag: "not cli and locking"
            name: "not_cli_and_locking"
        config:
          - path: "../params/br-ne1.yaml"
            name: "ne1"
          - path: "../params/br-se1.yaml"
            name: "se1"

    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{matrix.marker.name}}_${{matrix.config.name}}" # Combination of values to represent the test
      test: "*_test.py"
      config: "${{ matrix.config.path }}"
      # no multiple workers here just to make it easier to audit the logs (more verbosity with INFO level)
      flags: "--no-header -v -n auto --log-cli-level INFO --color=no -m '${{matrix.marker.flag}}'"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  cleanup-tests:
    needs: [run-locking-tests]
    if: always()
    uses: ./.github/workflows/cleanup-tests.yml
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

      