name: Run Test - Pull Request

on:
    pull_request:
      types: [opened, synchronize, reopened]
      
jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        category:
          - acl
          - cold_storage
          - basic
          - presign
          # - locking
          # - policy
    uses: ./.github/workflows/run-tests.yml
    with:
      tests: "*_test.py"
      config: "../params.example.yaml"
      flags: "-v -n auto --color yes -m '${{ matrix.category }}' --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
  tests-success:
    runs-on: ubuntu-24.04
    needs: [run-tests]
    steps:
      - name: ok
        run:
          exit 0
