# Tests that must pass in order for a PR to be allowed on the main branch
# it is expected that they finish fast, thal ALL tests pass
# and no verbose logging / debugging is enabled.
#
# They should run as much as possible in parallel.

name: Pull Request Essential Tests

on:
    pull_request:
      types: [ready_for_review]

jobs:
  run_tests:
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        marker:
          - test: cold_storage
            name: cold_storage
          - test: basic
            name: basic
          - test: presign
            name: presign
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  tests-success:
    runs-on: ubuntu-24.04
    needs: [run_tests]
    steps:
      - name: ok
        run:
          exit 0

  # cleanup-tests:
  #   needs: [tests-success]
  #   if: always() 
  #   uses: ./.github/workflows/cleanup-tests.yml
  #   secrets:
  #     PROFILES: ${{ secrets.PROFILES }}
