# Tests that for one reason or another we dont want to make it a blocker for PRs
# it may be because they are slow, or because tey include features still in 
# preview/not fully launched.
#
# It's ok for the output to be verbose as they might be here to help in the debugging
# of some behavior/flakiness.
#
# It's ok for tests here to fail or to be slow. They should not block any CI pipelines.
#
# Here we also run the tests on both regions.

name: Pull Request Extra Tests

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # tests that we are not debugging at the moment,
  # tests that can run in parallel with pytest-xdist
  # it's ok to run only on br-ne1
  extra_tests_dist:
    strategy:
      fail-fast: false
      matrix:
        marker:   # Redundancy is necessary since names must have no spaces
          - test: bucket_versioning
            name: bucket_versioning
          - test: policy
            name: policy
          - test: acl
            name: acl
        config:
          - path: "../params/br-ne1.yaml"
            name: "br_ne1"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}.${{ matrix.config.name }}"
      config: "${{ matrix.config.path }}"
      flags: "-v -n auto --color yes -m '${{ matrix.marker.test }}' --tb=line"
      # runner: "self-hosted"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  # tests that we want to see all logging messages
  # tests that we want to test on both regions
  extra_tests_debug:
    strategy:
      fail-fast: false
      matrix:
        marker:
          - test: locking
            name: locking
        config:
          - path: "../params/br-ne1.yaml"
            name: "br_ne1"
          - path: "../params/br-se1.yaml"
            name: "br_se1"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}.${{ matrix.config.name }}"
      config: "${{ matrix.config.path }}"
      flags: "-v --log-cli-level INFO --color yes -m '${{ matrix.marker.test }}'"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  cleanup_tests:
    needs: [extra_tests_debug, extra_tests_dist]
    if: always()
    uses: ./.github/workflows/cleanup-tests.yml
    secrets:
      PROFILES: ${{ secrets.PROFILES }}


