# Tests that must pass in order for a PR to be allowed on the main branch
# it is expected that they finish fast, thal ALL tests pass
# and no verbose logging / debugging is enabled.
#
# They should run as much as possible in parallel.

name: Pull Request Essential Tests

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  run_tests:
    strategy:
      fail-fast: true
      matrix:
        category:
          - test: cold_storage
            name: cold_storage
          - test: basic
            name: basic
          - test: presign
            name: presign
        config:
          - param: "../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.category.name }}.${{ matrix.config.name }}"
      config: ${{ matrix.config.param}}
      flags: "--no-header -vv -n auto --tb=short --color=no -m ${{ matrix.category }} --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  tests-success:
    runs-on: ubuntu-24.04
    needs: [run_tests]
    steps:
      - name: ok
        run:
          exit 0

  # since locking is a feature currently under preview, we run it separatedely
  # and dont block merges if they fail
  run-locking-tests:
    strategy:
      fail-fast: false
      matrix:
        category:
          - param: not cli and locking
            name: not_cli_and_locking
        config:
          - param: "../params/br-ne1.yaml"
            name: "br_ne1"
          - param: "../params/br-se1.yaml"
            name: "br_se1"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.category.name }}.${{ matrix.config.name }}"
      config: "${{ matrix.config.param }}"
      # no multiple workers here just to make it easier to audit the logs (more verbosity with INFO level)
      flags: "--no-header -vv -n auto --tb=short --color no -m ${{matrix.category.param}}"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  cleanup-tests:
    needs: [tests-success, run-locking-tests]
    if: always() 
    uses: ./.github/workflows/cleanup-tests.yml
    secrets:
      PROFILES: ${{ secrets.PROFILES }}