name: Recurrent tests

on:
  push:
    branches:
      - fix-recurrent-tests
  schedule:
    - cron: "0 */2 * * *"       # Every hour at 00 min
    - cron: "15 */6 * * *"     # Every 6 hours at *h30 min  
    - cron: "30 */12 * * *"    # Every 12 hours at *h15 min  

jobs:
  run_1h_tests:
    if: github.event.schedule == '0 */2 * * *'  
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        profile:
          - br-se1
          - br-ne1
        marker:
          # 1h tests
          - test: "'basic or cold_storage or presign'"
            name: "'basic or cold_storage or presign'"
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_1hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      profile: ${{ matrix.profile }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  run_6h_tests:
    if: github.event.schedule == '15 */6 * * *'
    strategy:
      max-parallel: 2
      fail-fast: false

      matrix:
        profile:
          - br-se1
          - br-ne1
        marker:
            # 6h tests
          - test: "acl or locking"
            name: "acl or locking"
          - test: "policy or bucket_versioning"
            name: "policy or bucket_versioning"
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_6hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      profile: ${{ matrix.profile }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}

  run_12h_tests:
    if: github.event.schedule == '30 */12 * * *'  
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        profile:
          - br-se1
          - br-ne1
        marker:
           # 12h tests
          - test: "multiple_objects or big_objects"
            name: "multiple_objects or big_objects"
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_12hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      profile: ${{ matrix.profile }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}


  # cleanup-tests:
  #   needs: [run_1h_tests]
  #   if: always() 
  #   uses: ./.github/workflows/cleanup-tests.yml
  #   secrets:
  #     PROFILES: ${{ secrets.PROFILES }}
