name: Recurrent 12h tests

on:
  schedule: 
    - cron: "30 */12 * * *"    # Every 12 hours at HH:30
  workflow_dispatch:

jobs:
  run_12h_tests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        profile:
          - br-se1
          - br-ne1
        marker:
          - test: "'multiple_objects or big_objects'"
            name: "'multiple_objects or big_objects'"
        config:
          - path: "../../../params.example.yaml"
            name: "example"
    uses: ./.github/workflows/run-tests.yml
    with:
      name: "${{ matrix.marker.name }}_12hours.${{ matrix.config.name }}"
      config: ${{ matrix.config.path }}
      profile: ${{ matrix.profile }}
      flags: "--no-header -vv -n auto --tb=line --color=no -m ${{ matrix.marker.test }} --tb=line --log-cli-level=info"
    secrets:
      PROFILES: ${{ secrets.PROFILES }}
