name: Run Tests

on:
    workflow_call:
      inputs:
        tests: { required: true, type: string }
        config: { required: true, type: string }
        flags: { required: true, type: string }
      secrets:
        PROFILES: { required: true }
jobs:
    build:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/marmotitude/s3-tester:tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
              
            - name: Install Poetry Dependences
              run: |
                  poetry install --quiet
                  
            - name: Configure Profiles
              run: |
                echo "${{ secrets.PROFILES }}" > profiles.yaml

                sha256sum profiles.yaml
                sha256sum ./bin/configure_profiles.py
                
                echo "Configuring Profiles..."
                poetry run python ./bin/configure_profiles.py ./profiles.yaml
                
            - name: Run tests ${{ inputs.tests }}
              run: |
                cd docs
                poetry run pytest --config ${{ inputs.config }} ${{ inputs.tests }} ${{ inputs.flags }}
