name: Run Tests

on:
    workflow_call:
      inputs:
        name: {required: true, type: string, default: "run_test"}
        tests: { required: false, type: string, default: "*_test.py"}
        config: { required: true, type: string }
        flags: { required: true, type: string }
        runner: { required: false, type: string, default: "ubuntu-24.04" }
        mgc_version: { required: false, type: string, default: "0.34.0" }
      secrets:
        PROFILES: { required: true }
jobs:
    build:
        runs-on: ${{ inputs.runner }}
        container:
          image: ghcr.io/marmotitude/s3-tester:tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "0.5.9"
              
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"

            - name: Install the project
              run: uv sync --no-dev

            - name: Install MGC
              run: |
                MGC_VERSION="${{ inputs.mgc_version }}"
                curl -Lo mgc.tar.gz "https://github.com/MagaluCloud/mgccli/releases/download/v${MGC_VERSION}/mgccli_${MGC_VERSION}_linux_amd64.tar.gz"
                tar xzvf mgc.tar.gz 
                rm mgc.tar.gz
                cp "./mgc" /usr/local/bin/mgc

            - name: Configure Profiles
              run: |
                echo "${{ secrets.PROFILES }}" > profiles.yaml
                sha256sum profiles.yaml
                sha256sum ./bin/configure_profiles.py
                echo "Configuring Profiles..."
                uv run python ./bin/configure_profiles.py ./profiles.yaml

            - name: Format input name
              id: format_name
              run: |
                  FORMATTED_NAME="$(echo "${{ inputs.name }}" | sed 's/[^a-zA-Z0-9.]/_/g')"
                  echo "formatted_name=$FORMATTED_NAME.${{ github.run_id }}" >> "$GITHUB_OUTPUT"
                  echo "formatted_log_name=$FORMATTED_NAME.$(date +'%Y%m%dT%H%M%S')" >> "$GITHUB_OUTPUT"

            - name: Run tests ${{ inputs.name }}
              shell: bash
              run: |
                cd src/s3_specs/docs
                mkdir -p /s3-specs/artifact/
                set -o pipefail
                uv run pytest --config ${{ inputs.config }} ${{inputs.tests}} ${{ inputs.flags }} | tee /s3-specs/artifact/actions_pytest_output_${{ steps.format_name.outputs.formatted_log_name }}.log
      
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: output_artifact_${{ steps.format_name.outputs.formatted_name }}
                path: "/s3-specs/artifact/actions_pytest_output_${{ steps.format_name.outputs.formatted_log_name }}.log"