name: Run Tests

on:
    workflow_dispatch:
      inputs:
        tests:
          description: 'Digite o nome do arquivo de teste a ser executado'
          required: true
        config:
          description: 'Digite o caminho da configuração a ser utilizado'
          required: true
          default: ../params.example.yaml
      

jobs:
    build:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/marmotitude/s3-tester:tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Install Poetry Dependences
              run: |
                  poetry install --quiet
                  
            - name: Configure Profiles
              run: |
                echo "${{ secrets.PROFILES }}" > profiles.yaml

                sha256sum profiles.yaml
                sha256sum ./bin/configure_profiles.py
                
                echo "Configuring Profiles..."
                poetry run python ./bin/configure_profiles.py ./profiles.yaml
                
            - name: Run tests
              run: |
                cd docs
                poetry run pytest --config ${{ inputs.config }} ${{ inputs.tests }}
